version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ims-backend
    volumes:
      - ./backend:/var/www
    ports:
      - "9000:9000"
    networks:
      - ims-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ims-frontend
    volumes:
      - ./frontend:/app
    ports:
    - "5173:5173"
    networks:
      - ims-net

  nginx:
    image: nginx:alpine
    container_name: ims-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - ims-net

networks:
  ims-net:
    driver: bridge
